import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Brain, Info } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import IntelligenceConfigSection from '@/components/admin/IntelligenceConfigSection';
import IntelligenceRulesSection from '@/components/admin/IntelligenceRulesSection';
import IntelligenceVersionSection from '@/components/admin/IntelligenceVersionSection';

export default function MinistryIntelligenceAdmin() {
  return (
    <div className="space-y-6">
      <Link to="/administration" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">
        <ArrowLeft className="h-4 w-4" /> Back to Administration
      </Link>
      <PageHeader
        title="Ministry Intelligence Engine"
        subtitle="Deterministic ministry rules, organizational thresholds, and relationship health calculations."
      />

      <section className="rounded-xl border bg-card p-5 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-full bg-muted">
            <Info className="h-5 w-5 text-muted-foreground" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">Overview</h2>
            <p className="text-sm text-muted-foreground">How the Ministry Intelligence Engine works.</p>
          </div>
        </div>
        <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
          The Ministry Intelligence Engine uses deterministic ministry rules and configurable thresholds to identify
          relationship opportunities, stewardship trends, leadership development, and organizational health. These
          settings influence ministry insights throughout Champion Connect but do not control the Ministry Coach AI.
        </p>
        <div className="mt-3 flex items-start gap-2 rounded-lg bg-muted/50 p-3">
          <Brain className="h-4 w-4 shrink-0 text-muted-foreground mt-0.5" />
          <p className="text-xs text-muted-foreground">
            <span className="font-medium text-foreground">Deterministic, not AI.</span> All signals generated by this
            engine follow fixed, explainable ministry rules. No artificial intelligence is involved in threshold
            evaluation or signal generation. AI configuration lives on the separate Ministry Coach Administration page.
          </p>
        </div>
      </section>

      <IntelligenceConfigSection />
      <IntelligenceRulesSection />
      <IntelligenceVersionSection />
    </div>
  );
}